packages:
  - name: indico
    environment:
      INDICO_AUTH: "${INDICO_AUTH}"
      MONGO_AUTH: "${MONGO_AUTH}"
    functions:
      - name: events
        runtime: go:1.20
        web: false
        limits:
          timeout: 15000
        triggers:
        - name: events
          sourceType: scheduler
          sourceDetails:
            cron: "0 0 * * *"
      - name: timetables
        runtime: go:1.20
        web: false
        limits:
          timeout: 30000
        triggers:
        - name: timetables
          sourceType: scheduler
          sourceDetails:
            cron: "15 0 * * *"
      - name: contributions
        runtime: go:1.20
        web: false
        limits:
          timeout: 180000
        triggers:
          - name: contributions
            sourceType: scheduler
            sourceDetails:
              cron: "30 0 * * *"
      - name: find
        runtime: go:1.20
        web: true
        limits:
          timeout: 5000
      - name: conferences
        runtime: go:1.20
        web: true
        limits:
          timeout: 5000